import test from 'node:test';
import assert from 'node:assert/strict';

import { validateTableSpec, generateTableSource, idKey, MAX_TABLE_NAME } from '../src/servicenow/dba-authoring.js';

/*
 * DBA Layer 3 — the offline half.
 *
 * Spec validation and codegen are pure, which is the whole design: the source
 * that reaches `now-sdk build` is DERIVED from a structured spec, never
 * generated by the model, so it can be asserted exactly rather than sampled.
 *
 * `now-sdk build` is offline and free, so it is the real second gate. These
 * tests cover what a build cannot tell you — whether the emitted source says
 * what the spec asked for.
 */

const SCOPE = 'x_2002152_nwforge';

const SPEC = {
  name: `${SCOPE}_asset`,
  label: 'DBA Demo Asset',
  display: 'u_name',
  fields: [
    { name: 'u_name', type: 'string', label: 'Name', maxLength: 100, mandatory: true },
    { name: 'u_owner', type: 'reference', label: 'Owner', reference: 'sys_user' },
    { name: 'u_status', type: 'choice', label: 'Status', choices: { active: 'Active', retired: 'Retired' }, default: 'active' },
  ],
  acls: [{ operation: 'read', roles: ['itil'] }],
};

const norm = (over = {}) => validateTableSpec({ ...SPEC, ...over }, { scope: SCOPE }).normalized;

/* ── validation ───────────────────────────────────────────────────────────── */

test('a well-formed scoped spec validates', () => {
  const v = validateTableSpec(SPEC, { scope: SCOPE });
  assert.equal(v.ok, true, v.errors.join('; '));
});

test('a table name must carry the scope prefix', () => {
  const v = validateTableSpec({ ...SPEC, name: 'asset' }, { scope: SCOPE });
  assert.equal(v.ok, false);
  assert.match(v.errors[0], /must start with the scope prefix/);
});

test(`the ${MAX_TABLE_NAME}-character cap is enforced at the spec, not at build time`, () => {
  const v = validateTableSpec({ ...SPEC, name: `${SCOPE}_a_very_long_table_name_here` }, { scope: SCOPE });
  assert.equal(v.ok, false);
  assert.match(v.errors.join(' '), /capped at 30 characters/);
  // The message must say how much room the prefix actually leaves.
  assert.match(v.errors.join(' '), /leaves 12 characters/);
});

test('a single-letter column name is legal', () => {
  // The first regex here required two characters and rejected this, then that
  // error masked every other problem in the same spec.
  const v = validateTableSpec({ ...SPEC, display: 'a', fields: [{ name: 'a', type: 'string' }] }, { scope: SCOPE });
  assert.equal(v.ok, true, v.errors.join('; '));
});

test('an unsupported column type is named, with the supported list', () => {
  const v = validateTableSpec({ ...SPEC, fields: [{ name: 'x', type: 'blob' }] }, { scope: SCOPE });
  assert.match(v.errors.join(' '), /type "blob", which this authoring layer does not emit/);
  assert.match(v.errors.join(' '), /string, integer, boolean, reference, choice/);
});

test('a reference column without a target, and a choice column without choices, are refused', () => {
  assert.match(validateTableSpec({ ...SPEC, fields: [{ name: 'x', type: 'reference' }] }, { scope: SCOPE }).errors.join(' '), /must name the table it points at/);
  assert.match(validateTableSpec({ ...SPEC, fields: [{ name: 'x', type: 'choice' }] }, { scope: SCOPE }).errors.join(' '), /must supply choices/);
});

test('display must name a column that exists', () => {
  assert.match(validateTableSpec({ ...SPEC, display: 'nope' }, { scope: SCOPE }).errors.join(' '), /not one of the columns/);
});

test('a duplicate column is caught', () => {
  const v = validateTableSpec({ ...SPEC, fields: [{ name: 'a', type: 'string' }, { name: 'a', type: 'string' }] }, { scope: SCOPE });
  assert.match(v.errors.join(' '), /defined twice/);
});

test('allowWebServiceAccess defaults ON and must be opted out of explicitly', () => {
  // §1.7: without it the Table API answers 403 with perfectly correct ACLs.
  assert.equal(norm().allowWebServiceAccess, true);
  assert.equal(norm({ allowWebServiceAccess: false }).allowWebServiceAccess, false);
});

/* ── codegen ──────────────────────────────────────────────────────────────── */

test('the Table is a NAMED EXPORT matching the table name', () => {
  // MEASURED: a bare Table({...}) fails the build with
  // TS213 "Table definition should be exported as a named export with the name ..."
  const src = generateTableSource(norm());
  assert.match(src, new RegExp(`export const ${SCOPE}_asset = Table\\(`));
});

test('every $id key is namespaced by the table name', () => {
  // Trap #1: $id keys are a PROJECT-GLOBAL namespace. A bare key like "table"
  // collides with every other source file in the workspace.
  const src = generateTableSource(norm());
  const keys = [...src.matchAll(/Now\.ID\["([^"]+)"\]/g)].map((m) => m[1]);
  assert.ok(keys.length >= 2, 'expected a table id and at least one ACL id');
  for (const k of keys) assert.ok(k.startsWith(`${SCOPE}_asset`), `${k} is not namespaced by the table`);
  assert.equal(new Set(keys).size, keys.length, 'ids must be unique within the file');
  assert.equal(idKey('t', 'table'), 't_table');
});

test('only the column factories actually used are imported', () => {
  const src = generateTableSource(norm({ fields: [{ name: 'u_a', type: 'string' }], acls: [] }));
  assert.match(src, /import \{ Table, StringColumn \} from '@servicenow\/sdk\/core'/);
  assert.doesNotMatch(src, /BooleanColumn/);
  // No Acl import when there are no ACLs, and no empty slot in the import list.
  assert.doesNotMatch(src, /Acl/);
  assert.doesNotMatch(src, /,\s*,/);
});

test('a choice column emits its values as a choices map', () => {
  const src = generateTableSource(norm());
  assert.match(src, /"active": \{ label: "Active" \}/);
  assert.match(src, /"retired": \{ label: "Retired" \}/);
  assert.match(src, /default: "active"/);
});

test('a reference column emits referenceTable', () => {
  assert.match(generateTableSource(norm()), /ReferenceColumn\(\{ label: "Owner", referenceTable: "sys_user" \}\)/);
});

test('allowWebServiceAccess is always emitted, both ways', () => {
  assert.match(generateTableSource(norm()), /allowWebServiceAccess: true/);
  assert.match(generateTableSource(norm({ allowWebServiceAccess: false })), /allowWebServiceAccess: false/);
});

test('an ACL carries table, operation, roles and an explicit active flag', () => {
  const src = generateTableSource(norm());
  assert.match(src, /operation: "read"/);
  assert.match(src, /roles: \["itil"\]/);
  assert.match(src, new RegExp(`table: "${SCOPE}_asset"`));
  assert.match(src, /active: true/);
});

test('the generated header says the source is derived, not model-written', () => {
  assert.match(generateTableSource(norm()), /Deterministic/);
  assert.match(generateTableSource(norm()), /Edit the spec, not this source/);
});
