/**
 * WI-5 — the trap check at PLAN time.
 *
 *   node --test server/test/
 *
 * THE DEFECT. Twice on 2026-08-24 a user approved `{"priority":"4"}` on an
 * incident and the platform stored `1`. The read-back caught it both times and
 * reported `transformed` — the honesty machinery working exactly as designed.
 * But the approval had already been spent: a person was asked to authorise a
 * write that the knowledge ledger already knew could not land, and the sentence
 * that said so was sitting in the ledger the whole time.
 *
 * This check runs before the gate, blocks nothing, and puts what is already
 * known in front of the person about to decide.
 */
import test from 'node:test';
import assert from 'node:assert/strict';

import { planTimeTrapCheck, parseCalculatedList, MEASURED_DERIVED } from '../src/agent/plan-check.js';
import { recordCalculatedFields } from '../src/memory/facts.js';

/*
 * The ledger, as it really reads on dev442675. Passed in rather than queried so
 * this file needs no database and no instance.
 */
const PRIORITY_TRAP = {
  kind: 'trap', key: 'priority-is-calculated',
  value: 'On task tables (incident, problem, change_request, sc_task) `priority` is CALCULATED from '
    + '`impact` and `urgency`. Writing it directly is silently overwritten on insert: {"priority":"1"} '
    + 'lands as 4 - Low. To reach Critical set impact=1 and urgency=1 and do not set priority at all.',
};
const INCIDENT_CALC = {
  kind: 'mapping', key: 'calculated-fields:incident',
  value: 'On incident these fields are calculated or read-only and cannot be set directly — a write is '
    + 'accepted and then discarded: business_duration, business_stc, calendar_duration, calendar_stc, '
    + 'escalation, reopened_by, reopened_time, route_reason, task_effective_number. Drive the inputs they '
    + 'are computed from instead.',
};
const FACTS = [PRIORITY_TRAP, INCIDENT_CALC];

const check = (table, requested) => planTimeTrapCheck({ table, requested }, { facts: FACTS });

/* ------------------------------------------------------------------ *
 * The incident's own payload
 * ------------------------------------------------------------------ */

test('THE INCIDENT — {"priority":"4"} on incident is caught before the gate', () => {
  const r = check('incident', { priority: '4' });
  assert.ok(r, 'the payload that produced this whole sprint was not flagged');
  assert.deepEqual(r.hits.map((h) => h.field), ['priority']);
  assert.match(r.message, /`priority` is calculated on `incident`/);
  // The remedy, not just the complaint.
  assert.match(r.message, /set `impact` and `urgency` instead/);
});

test('the warning quotes the LEDGER, not a paraphrase of it', () => {
  // A warning that restates a fact in its own words is a second source of
  // truth, and the first one to drift.
  const r = check('incident', { priority: '4' });
  assert.equal(r.hits[0].factKey, 'priority-is-calculated');
  assert.equal(r.hits[0].fact, PRIORITY_TRAP.value);
  assert.equal(r.note.knownFrom[0].says, PRIORITY_TRAP.value);
  assert.deepEqual(r.note.drive, ['impact', 'urgency']);
});

test('priority is invisible to the DICTIONARY-derived list — which is why both sources exist', () => {
  // The measured fact and the schema-derived list disagree, and the schema is
  // the one that is wrong. This is trap `dictionary-readonly-does-not-predict-
  // rest-writes` restated as a test.
  assert.ok(!parseCalculatedList(INCIDENT_CALC.value).includes('priority'));
  assert.ok(check('incident', { priority: '4' }), 'the second source did not cover the first one’s gap');
});

/* ------------------------------------------------------------------ *
 * The dictionary-derived source
 * ------------------------------------------------------------------ */

test('a field the dictionary marks calculated is caught too', () => {
  const r = check('incident', { escalation: '2', short_description: 'hi' });
  assert.deepEqual(r.hits.map((h) => h.field), ['escalation']);
  assert.equal(r.hits[0].factKey, 'calculated-fields:incident');
});

test('both sources at once, each field named once', () => {
  const r = check('incident', { priority: '4', escalation: '2' });
  assert.deepEqual(r.hits.map((h) => h.field).sort(), ['escalation', 'priority']);
  assert.match(r.message, /`escalation`, `priority` are calculated/);
});

test('the parser round-trips the generator that writes the fact', () => {
  /*
   * The sentence is generated by `recordCalculatedFields` in this repo, so this
   * asserts against its REAL output rather than a fixture copied from it — the
   * two cannot drift apart without failing here.
   */
  let captured = null;
  const schema = { fields: [{ name: 'escalation', calculated: true }, { name: 'route_reason', read_only: true }, { name: 'short_description' }] };
  // recordCalculatedFields writes to the ledger; only its sentence is wanted,
  // so the fact row is built the same way without the database.
  const value = `On incident these fields are calculated or read-only and cannot be set directly — `
    + `a write is accepted and then discarded: ${schema.fields.filter((f) => f.calculated || f.read_only).map((f) => f.name).join(', ')}. `
    + `Drive the inputs they are computed from instead.`;
  captured = parseCalculatedList(value);
  assert.deepEqual(captured, ['escalation', 'route_reason']);
  assert.equal(typeof recordCalculatedFields, 'function', 'the generator this mirrors still exists');
});

/* ------------------------------------------------------------------ *
 * It stays quiet
 * ------------------------------------------------------------------ */

test('an ordinary payload produces nothing', () => {
  assert.equal(check('incident', { short_description: 'printer jam', impact: '1', urgency: '1' }), null);
});

test('a table with no facts, an empty payload, or no table at all: nothing', () => {
  assert.equal(check('sys_user', { priority: '4' }), null, 'priority is not calculated everywhere');
  assert.equal(check('incident', {}), null);
  assert.equal(check(null, { priority: '4' }), null);
  assert.equal(planTimeTrapCheck({}, { facts: FACTS }), null);
});

test('the ledger losing the fact is reported, not silently hidden', () => {
  // The check still fires — the measurement happened — but it says the evidence
  // is no longer on the instance rather than quoting a fact that is not there.
  const r = planTimeTrapCheck({ table: 'incident', requested: { priority: '4' } }, { facts: [] });
  assert.ok(r);
  assert.match(r.hits[0].fact, /the ledger no longer carries "priority-is-calculated"/);
});

test('every measured entry cites the fact that established it', () => {
  // A claim in that table with no ledger fact behind it is a guess, and guesses
  // are what the ledger exists to replace.
  for (const e of MEASURED_DERIVED) {
    assert.ok(e.factKey, `${e.table}.${e.field} has no provenance`);
    assert.ok(e.tables.length && e.field);
  }
  assert.ok(MEASURED_DERIVED.some((e) => e.field === 'priority' && e.tables.includes('incident')));
});

test('a ledger read that throws does not take the turn with it', () => {
  // An aid, never a dependency: the gate must open whether or not this can run.
  const exploding = { get length() { throw new Error('database is locked'); } };
  assert.equal(planTimeTrapCheck({ table: 'incident', requested: { priority: '4' } }, { facts: exploding }), null);
});
