import test from 'node:test';
import assert from 'node:assert/strict';

import {
  sdkCatalogue,
  actionRules,
  parseBuiltIn,
  familyOf,
  builtInsDir,
} from '../src/servicenow/sdk-catalogue.js';
import { ACTION_CATALOGUE, ACTION_OUTPUTS, RECORD_TRIGGERS, SCHEDULED_TRIGGERS, APPLICATION_TRIGGERS } from '../src/servicenow/flow-design.js';

/**
 * THE CATALOGUE COMES FROM THE SDK, NOT FROM A DOCUMENT.
 *
 * These tests pin two different things. The parser tests are hermetic — they
 * parse a fixture and never touch the installed SDK. The catalogue tests read
 * the SDK that is actually installed in the workspace, and SKIP THEMSELVES when
 * it is absent rather than passing vacuously: "the SDK is not installed" and
 * "the SDK agrees with us" must never look alike.
 */

const FIXTURE = `
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.demoAction = void 0;
// This file is auto-generated by sync-plugin-apis.ts — do not edit directly.
const Action_1 = require("../../../Action");
const db_1 = require("@servicenow/sdk-core/runtime/db");
exports.demoAction = (0, Action_1.Action)({
    $id: 'aabbccddeeff00112233445566778899',
    name: 'Demo Action',
    description: 'Does a demo thing, with a { brace } in the prose.',
    inputs: {
        table_name: (0, db_1.TableNameColumn)({
            label: 'Table',
            mandatory: true,
        }),
        note: (0, db_1.StringColumn)({
            label: 'Note',
        }),
    },
    outputs: {
        Record: (0, db_1.DocumentIdColumn)({
            label: 'Record',
            dependent: 'table_name',
        }),
    },
});
`;

test('a generated built-in parses into its id, name, inputs and outputs', () => {
  const parsed = parseBuiltIn(FIXTURE, 'demoAction');
  assert.equal(parsed.sysId, 'aabbccddeeff00112233445566778899');
  assert.equal(parsed.name, 'Demo Action');
  assert.deepEqual(parsed.inputs.map((i) => [i.name, i.mandatory]), [['table_name', true], ['note', false]]);
  assert.equal(parsed.inputs[0].column, 'TableNameColumn');
  assert.deepEqual(parsed.outputs.map((o) => o.name), ['Record']);
  assert.equal(parsed.outputs[0].dependent, 'table_name');
});

test('a brace inside a description does not truncate the definition', () => {
  const parsed = parseBuiltIn(FIXTURE, 'demoAction');
  assert.match(parsed.description, /\{ brace \}/);
  assert.equal(parsed.inputs.length, 2, 'the inputs after the prose must still be found');
});

test('an export the file does not define parses as nothing, not as an empty action', () => {
  assert.equal(parseBuiltIn(FIXTURE, 'notThere'), null);
});

test('the trigger family is derived from the type the SDK declares', () => {
  assert.equal(familyOf('record_create'), 'record');
  assert.equal(familyOf('record_create_or_update'), 'record');
  assert.equal(familyOf('daily'), 'scheduled');
  assert.equal(familyOf('run_once'), 'scheduled');
  assert.equal(familyOf('service_catalog'), 'application');
  assert.equal(familyOf(null), null);
});

test('a missing SDK yields no catalogue and a reason — never a fabricated one', () => {
  const absent = sdkCatalogue({ workspace: 'C:/nowhere-at-all', refresh: true });
  assert.equal(absent.available, false);
  assert.match(absent.reason, /not installed/);
  assert.deepEqual(absent.actions, {});
  assert.equal(actionRules(absent), null, 'no catalogue is better than an invented one');
  sdkCatalogue({ refresh: true });   // restore the cache for the tests below
});

/* ---- against the SDK that is actually installed ---- */

const live = sdkCatalogue({ refresh: true });
const withSdk = (name, fn) => test(name, { skip: live.available ? false : `the SDK built-ins are not installed: ${live.reason}` }, fn);

withSdk('the installed SDK defines more actions than the cheatsheet documents', () => {
  assert.ok(live.counts.actions >= 30, `expected the full catalogue, got ${live.counts.actions}`);
  const documented = new Set(Object.keys(ACTION_CATALOGUE));
  const extra = Object.keys(live.actions).filter((k) => !documented.has(k));
  assert.ok(extra.length > 0, 'the SDK ships actions the documented table never listed');
  /* The attachment actions the cheatsheet named only as a category. */
  for (const a of ['copyAttachment', 'deleteAttachment', 'getAttachmentsOnRecord', 'moveAttachment']) {
    assert.ok(live.actions[a], `${a} should be in the SDK catalogue`);
  }
});

withSdk('every documented action really exists in the SDK, under that exact name', () => {
  const missing = Object.keys(ACTION_CATALOGUE).filter((k) => !live.actions[k]);
  assert.deepEqual(missing, [], 'a documented action the SDK does not define would be an invented one');
});

withSdk('there is no deleteMultipleRecords, which is why the linter names its replacement', () => {
  assert.equal(live.actions.deleteMultipleRecords, undefined);
  assert.ok(live.actions.deleteRecord, 'the single-record delete is what exists');
  assert.ok(live.actions.lookUpRecords, 'and lookUpRecords + forEach is the documented replacement');
});

withSdk('the SDK ships exactly the trigger forms the linter allows, and no record.deleted', () => {
  const byFamily = (f) => Object.entries(live.triggers).filter(([, t]) => t.family === f).map(([k]) => k).sort();
  assert.deepEqual(byFamily('record'), [...RECORD_TRIGGERS].sort());
  assert.deepEqual(byFamily('scheduled'), Object.keys(SCHEDULED_TRIGGERS).sort());
  assert.deepEqual(byFamily('application'), [...APPLICATION_TRIGGERS].sort());
  assert.equal(live.triggers.deleted, undefined, 'the SDK defines no record-deleted trigger');
});

withSdk('the record trigger requires a table, and only update-style triggers take a strategy', () => {
  const mandatory = (k) => live.triggers[k].inputs.filter((i) => i.mandatory).map((i) => i.name);
  assert.deepEqual(mandatory('created'), ['table']);
  const accepts = (k) => live.triggers[k].inputs.map((i) => i.name);
  assert.ok(accepts('updated').includes('trigger_strategy'));
  assert.ok(accepts('createdOrUpdated').includes('trigger_strategy'));
  assert.ok(!accepts('created').includes('trigger_strategy'), 'created has no strategy input at all');
});

withSdk('each scheduled form declares the parameters the linter demands of it', () => {
  for (const [form, need] of Object.entries(SCHEDULED_TRIGGERS)) {
    const mandatory = live.triggers[form].inputs.filter((i) => i.mandatory).map((i) => i.name).sort();
    assert.deepEqual(mandatory, [...need].sort(), form);
  }
});

withSdk('the output casing table agrees with the SDK for every action it covers', () => {
  for (const [name, documented] of Object.entries(ACTION_OUTPUTS)) {
    const real = live.actions[name].outputs.map((o) => o.name);
    for (const own of documented.own) {
      /* The documented list may carry outputs the SDK models differently; what
       * must never happen is the documented name differing only by CASE from a
       * real one, because that is the mistake the linter reports. */
      const clash = real.find((r) => r.toLowerCase() === own.toLowerCase() && r !== own);
      assert.equal(clash, undefined, `${name}: documented "${own}" vs SDK "${clash}"`);
    }
  }
});

withSdk('the SDK contradicts two "required" claims the documented table made', () => {
  const rules = actionRules(live);
  /* These are the entries that would have rejected correct source. Pinned so
   * that if a future SDK really does make them mandatory, this test says so. */
  assert.ok(!rules.lookUpRecord.requires.includes('table'), 'the SDK does not mark lookUpRecord.table mandatory');
  assert.ok(!rules.createTask.requires.includes('field_values'), 'the SDK does not mark createTask.field_values mandatory');
  assert.deepEqual(rules.createRecord.requires.sort(), ['table_name', 'values']);
  assert.deepEqual(rules.updateRecord.requires.sort(), ['record', 'table_name', 'values']);
});

withSdk('every action carries the sys_id of its live action-type record', () => {
  for (const [name, a] of Object.entries(live.actions)) {
    assert.match(a.sysId ?? '', /^[0-9a-f]{32}$/, `${name} should carry a 32-hex action type id`);
  }
  assert.ok(builtInsDir(), 'the built-ins directory resolves');
});

/* ------------------------------------------------------------------ *
 * Gate mode — local checks enforce by default
 * ------------------------------------------------------------------ */

test('the gate mode is read from the environment, and anything unrecognised enforces', async () => {
  const { flowGateMode, FLOW_GATE_MODES } = await import('../src/servicenow/fluent.js');
  const before = process.env.NOWFORGE_FLOW_GATES;
  try {
    delete process.env.NOWFORGE_FLOW_GATES;
    assert.equal(flowGateMode(), 'enforce', 'the default must stop bad generated source before install');

    process.env.NOWFORGE_FLOW_GATES = 'enforce';
    assert.equal(flowGateMode(), 'enforce');

    process.env.NOWFORGE_FLOW_GATES = 'ENFORCE';
    assert.equal(flowGateMode(), 'enforce', 'case is not a reason to silently change mode');

    process.env.NOWFORGE_FLOW_GATES = 'off';
    assert.equal(flowGateMode(), 'enforce', 'an unknown value must not weaken the gate');

    assert.deepEqual([...FLOW_GATE_MODES], ['advisory', 'enforce']);
  } finally {
    if (before === undefined) delete process.env.NOWFORGE_FLOW_GATES;
    else process.env.NOWFORGE_FLOW_GATES = before;
  }
});

test('advisory mode changes what a finding DOES, never whether the check runs', async () => {
  const { lintFlowDesign } = await import('../src/servicenow/flow-design.js');
  /* The linters are pure and mode-free by construction: nothing in them reads
   * the environment. That is what makes "preserved, not deleted" checkable. */
  const bad = `
Flow({ $id: Now.ID['x'], name: 'X' },
  wfa.trigger(trigger.record.created, { $id: Now.ID['t'] }, { table: 'incident', run_flow_in: 'sync' }),
  () => { wfa.action(action.core.createRecord, { $id: Now.ID['a'] }, { table: 'incident' }) }
)`;
  const before = process.env.NOWFORGE_FLOW_GATES;
  try {
    process.env.NOWFORGE_FLOW_GATES = 'advisory';
    const advisory = lintFlowDesign(bad);
    process.env.NOWFORGE_FLOW_GATES = 'enforce';
    const enforcing = lintFlowDesign(bad);
    assert.deepEqual(advisory.errors, enforcing.errors, 'the same findings in both modes');
    assert.ok(advisory.errors.length >= 2, 'and they are real findings');
  } finally {
    if (before === undefined) delete process.env.NOWFORGE_FLOW_GATES;
    else process.env.NOWFORGE_FLOW_GATES = before;
  }
});
