"""
SAOS — ServiceNow Tool Contract
Defines ONLY the narrow, scoped read methods agents are allowed to use.
Agents MUST NOT receive an arbitrary REST client.
DO NOT add: servicenow_request(method, url, payload) — ever.
"""
from __future__ import annotations

from typing import Any, Protocol


class ServiceNowReadContract(Protocol):
    """
    The only interface agents receive.
    All methods are read-only. Narrowly scoped.
    """

    async def get_ci(self, ci_id: str) -> dict[str, Any]: ...
    async def search_cis(self, filters: dict[str, Any], limit: int = 100) -> list[dict[str, Any]]: ...
    async def get_ci_relationships(self, ci_id: str, depth: int = 2) -> list[dict[str, Any]]: ...
    async def get_cmdb_health(self) -> dict[str, Any]: ...

    async def get_discovery_status(self, ci_id: str) -> dict[str, Any]: ...
    async def get_discovery_results(self, ci_id: str) -> list[dict[str, Any]]: ...

    async def get_mid_servers(self) -> list[dict[str, Any]]: ...
    async def get_mid_health(self, mid_id: str) -> dict[str, Any]: ...
    async def get_ecc_queue_status(self) -> dict[str, Any]: ...

    async def get_service_map(self, service_id: str) -> dict[str, Any]: ...
    async def get_alerts_for_ci(self, ci_id: str) -> list[dict[str, Any]]: ...
    async def get_problem_records(self) -> list[dict[str, Any]]: ...
    async def get_incidents_for_ci(self, ci_id: str) -> list[dict[str, Any]]: ...
    async def get_change_records_for_ci(self, ci_id: str) -> list[dict[str, Any]]: ...

    async def simulate_ire(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def get_audit_history(self, table: str, sys_id: str) -> list[dict[str, Any]]: ...
    async def get_source_metadata(self, ci_id: str) -> dict[str, Any]: ...

    async def get_all_cis(self, limit: int = 500) -> list[dict[str, Any]]: ...
    async def get_mid_server_list(self) -> list[dict[str, Any]]: ...
    async def get_service_maps(self) -> list[dict[str, Any]]: ...
    async def get_all_alerts(self) -> list[dict[str, Any]]: ...
    async def get_cloud_accounts(self) -> list[dict[str, Any]]: ...
    async def get_cloud_resources(self) -> list[dict[str, Any]]: ...
    async def get_metric_feeds(self) -> list[dict[str, Any]]: ...
    async def get_discovery_schedules(self) -> list[dict[str, Any]]: ...
    async def get_credential_records(self) -> list[dict[str, Any]]: ...
    async def get_all_relationships(self, limit: int = 500) -> list[dict[str, Any]]: ...
    async def get_all_incidents(self, limit: int = 200) -> list[dict[str, Any]]: ...
    async def get_all_change_requests(self, limit: int = 200) -> list[dict[str, Any]]: ...
    async def get_all_problems(self, limit: int = 200) -> list[dict[str, Any]]: ...


# Allowed execution action types (for RemediationExecutor ONLY)
ALLOWED_EXECUTION_ACTIONS = frozenset({
    "update_ci_field",
    "create_ci_relationship",
    "retire_ci_relationship",
    "update_lifecycle",
    "update_reference",
    "trigger_discovery",
    "trigger_health_recalculation",
    "merge_duplicate_ci",
    "update_ci_class",
})
